<?php
namespace Fobia\Database\SphinxConnection\Test\Eloquent\Query;

use Fobia\Database\SphinxConnection\Test\TestCase;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-08 at 13:17:38.
 */
class GrammarTest extends TestCase
{
    /**
     * @var Grammar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    //protected function setUp()
    //{
    //    $this->object = new Grammar;
    //}

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    //protected function tearDown()
    //{
    //}

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::compileSelect
     * @todo   Implement testCompileSelect().
     */
    public function testCompileSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::compileGrouporders
     * @todo   Implement testCompileGrouporders().
     */
    public function testCompileGrouporders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::compileOptions
     * @todo   Implement testCompileOptions().
     */
    public function testCompileOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::compileFacets
     * @todo   Implement testCompileFacets().
     */
    public function testCompileFacets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::compileLimit
     * @todo   Implement testCompileLimit().
     */
    public function testCompileLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::compileOffset
     * @todo   Implement testCompileOffset().
     */
    public function testCompileOffset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::compileFrom
     * @todo   Implement testCompileFrom().
     */
    public function testCompileFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::compileMatch
     * @todo   Implement testCompileMatch().
     */
    public function testCompileMatch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::compileWheres
     * @todo   Implement testCompileWheres().
     */
    public function testCompileWheres()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::wrap
     * @todo   Implement testWrap().
     */
    public function testWrap()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::wrapValue
     * @todo   Implement testWrapValue().
     */
    public function testWrapValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::wrapValue2
     * @todo   Implement testWrapValue2().
     */
    public function testWrapValue2()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Query\Grammar::parameter
     * @todo   Implement testParameter().
     */
    public function testParameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
