<?php
namespace Fobia\Database\SphinxConnection\Test\Eloquent;

use Fobia\Database\SphinxConnection\Test\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-08 at 13:16:59.
 */
class ModelTest extends TestCase
{
    /**
     * @var Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    //protected function setUp()
    //{
    //    $this->object = new Model;
    //}

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    //protected function tearDown()
    //{
    //}

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Model::filterParamsUint
     * @todo   Implement testFilterParamsUint().
     */
    public function testFilterParamsUint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Model::getMvaAttribute
     * @todo   Implement testGetMvaAttribute().
     */
    public function testGetMvaAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Model::asMva
     * @todo   Implement testAsMva().
     */
    public function testAsMva()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Model::castAttribute
     * @todo   Implement testCastAttribute().
     */
    public function testCastAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Model::newQueryWithoutScopes
     * @todo   Implement testNewQueryWithoutScopes().
     */
    public function testNewQueryWithoutScopes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Model::newEloquentBuilder
     * @todo   Implement testNewEloquentBuilder().
     */
    public function testNewEloquentBuilder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Model::newBaseQueryBuilder
     * @todo   Implement testNewBaseQueryBuilder().
     */
    public function testNewBaseQueryBuilder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Fobia\Database\SphinxConnection\Eloquent\Model::getConnection
     * @todo   Implement testGetConnection().
     */
    public function testGetConnection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
